version: '3'
services:

  gt-layout-service:
    build: ./service
    image: "gt-layout-service"

  cxmate:
    build: ./cxmate
    image: "gt-layout-cxmate"
    ports:
     - "80:80"
    links:
     - gt-layout-service
